---
abstract: 'steal lexical variables from your caller'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Lexical::Thief
name: Acme-Lexical-Thief
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Keyword::Simple: 0
  PadWalker: 0
  perl: 5.12.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Acme-Lexical-Thief
  homepage: https://metacpan.org/release/Acme-Lexical-Thief
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-acme-lexical-thief
version: 0.001
